<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * @param $limit
     * @param null $offset
     * @return array
     */
    public function findNewest($limit, $offset = null)
    {
        return $this->findBy([], ['dateAdded' => 'desc'], $limit, $offset);
    }
}
